name: Health

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # healthcheck:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Comprobar estado de la app
  #       uses: dawidd6/action-http-client@v3
  #       with:
  #         url: http://${{ secrets.AWS_HOSTNAME }}
  #         method: GET
  #         timeout: 10
  #         expected_status: 200

  healthcheck:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Comprobar estado de la app
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.AWS_HOSTNAME }}
          max-attempts: 5
          retry-delay: 5
          retry-all: true

